baseURL = "https://slashpai.github.io/presentations"
languageCode = "en-us"
title = "Presentations"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false

[params.reveal_hugo]
highlight_theme = "github"

[params.reveal_hugo.templates.yellow]
background = "#f6f195"
transition = "slide-in fade-out"

[params.reveal_hugo.templates.blue]
background = "#a5e2fd"
transition = "slide-in fade-out"
